version: "3.8"
services:
  postgresEx:
    image: postgres
    container_name: postgresPromo
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=promocode
    ports:
      - "5454:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
